export { socialLinks } from './site-data.js'

// Las fechas de tienda deben sustituirse por una fuente sincronizada cuando esté disponible.
// Actualiza estas fechas únicamente cuando la versión correspondiente ya esté publicada.
export const catalogMeta = {
  es: { lastUpdated: null, source: 'stores' },
  en: { lastUpdated: null, source: 'stores' },
}

export const releaseNotes = [
  {
    version: '3.0.0',
    releasedAt: 'Sep 14, 2026',
    dateSource: 'stores',
    es: {
      title: 'Nueva imagen oficial, 16 nuevos cantos y estudio avanzado',
      summary:
        'Actualización mayor con rediseño del icono oficial, pantalla de inicio renovada, 16 pistas de ensayo por voces (con énfasis especial en cantos del 15 de Septiembre en conmemoración del cumpleaños de nuestra hermana Eva García), conectividad Bluetooth reforzada, exportación a WhatsApp, anotaciones persistentes y modo oscuro OLED.',
      newScores: [],
      newAudio: [
        'A Los Pies Del Salvador (Confianza, Esperanza)',
        'A Veces me Pregunto (Gracia, Gratitud)',
        'Adorno en tu Corona (Elección)',
        'Como en Jericó (Oración)',
        'Como la Aurora (Elección, Honra)',
        'El Pescador (Advenimiento, Amor)',
        'El Pueblo Feliz (Honra)',
        'Es Honorable (Elección)',
        'El Hijo Pródigo (Llamamiento, Restauración)',
        'Joya Perfecta (Elección)',
        'Le Saludamos de Corazón (15 De Septiembre)',
        'Mujer Bendita de Dios (15 De Septiembre)',
        'Mujer de Gran Valor (15 De Septiembre)',
        'Nuestros Deseos (15 De Septiembre)',
        'Siempre Feliz (Adoración, Gratitud)',
        'Una Hermosura de Dios (15 De Septiembre)',
      ],
      changes: [
        'Nuevo icono oficial de la aplicación con bordes pulidos y compatibilidad nativa con Android e iOS (iconos adaptativos y temáticos).',
        'Pantalla de inicio renovada (Splash Screen) con apertura sobria y transición de difuminado suave (fade-in / fade-out) adaptada a cada tema.',
        '16 nuevos cantos con pistas de ensayo completas por voces (Soprano, Contralto, Tenor y Bajo), destacando los 5 cantos con tema 15 de Septiembre en honor al cumpleaños de nuestra hermana Eva García.',
        'Soporte reforzado para audio Bluetooth en bocinas externas y consolas de templos, eliminando problemas de latencia y cortes de señal.',
        'Exportación directa a WhatsApp en formato MP3 estándar compatible para reproducción instantánea en chats.',
        'Acceso directo a mezclador SATB y selector de velocidad desde la barra de reproducción.',
        'Anotaciones permanentes vinculadas a la partitura: tus notas y marcas ya no se sobrescriben con futuras actualizaciones de catálogo.',
        'Navegación horizontal tipo carrusel con paso de página instantáneo mediante gestos y toques.',
        'Rendimiento optimizado en el visor y zoom ultra fluido sin pérdida de nitidez.',
        'Modo Oscuro OLED con negro puro (#000000) para evitar reflejos de luz en cultos de oración nocturnos y ahorrar batería.',
        'Biblioteca local blindada 100% offline para abrir cualquier partitura o recurso en el templo sin conexión a internet.',
        'Sincronización bilingüe instantánea entre catálogo en español e inglés.',
      ],
    },
    en: {
      title: 'New official visual identity, 16 new rehearsal tracks & enhanced study',
      summary:
        'Major release featuring a redesigned official app icon, refreshed splash screen, 16 new rehearsal audio tracks with individual SATB parts (highlighting September 15th birthday commemoration hymns for Sister Eva García), Bluetooth streaming, WhatsApp export, permanent annotations, and OLED dark mode.',
      newScores: [],
      newAudio: [
        'A Los Pies Del Salvador (Trust, Hope)',
        'A Veces me Pregunto (Grace, Gratitude)',
        'Adorno en tu Corona (Election)',
        'Como en Jericó (Prayer)',
        'Como la Aurora (Election, Honor)',
        'El Pescador (Advent, Love)',
        'El Pueblo Feliz (Honor)',
        'Es Honorable (Election)',
        'El Hijo Pródigo (Calling, Restoration)',
        'Joya Perfecta (Election)',
        'Le Saludamos de Corazón (September 15th)',
        'Mujer Bendita de Dios (September 15th)',
        'Mujer de Gran Valor (September 15th)',
        'Nuestros Deseos (September 15th)',
        'Siempre Feliz (Worship, Gratitude)',
        'Una Hermosura de Dios (September 15th)',
      ],
      changes: [
        'New official application icon with polished curves and adaptive/themed system icon support for Android and iOS.',
        'Redesigned Splash Screen with smooth fade-in/fade-out transitions adapting to Day, Night, and OLED themes.',
        '16 new rehearsal audio tracks with individual SATB parts (Soprano, Alto, Tenor, Bass), featuring special September 15th commemoration hymns for Sister Eva García.',
        'Reinforced Bluetooth audio streaming for external speakers and temple sound systems without latency or dropouts.',
        'Direct WhatsApp export in standard MP3 format for immediate in-chat playback without external players.',
        'Quick access to SATB volume mixer and speed selector from the main player toolbar.',
        'Permanent score annotations: markings and notes remain tied to scores and are preserved across future catalog updates.',
        'Smooth carousel-style horizontal page turning via touch and gestures.',
        'Optimized graphics engine with lag-free zooming on high-resolution scores.',
        'Pure black OLED Dark Mode (#000000) for zero-glare night services and maximum battery efficiency.',
        'Rock-solid 100% offline library for opening scores and resources in temples without Wi-Fi or cellular service.',
        'Instant bilingual switching between English and Spanish scores without losing reading state.',
      ],
    },
  },
  {
    version: '2.5.2',
    releasedAt: 'Aug 26, 2026',
    dateSource: 'stores',
    es: {
      title: 'Más control para estudiar cada voz',
      summary: 'El reproductor MIDI, las anotaciones y el repertorio reciben una actualización amplia para hacer más cómodo el estudio.',
      newScores: [
        'Primer Centenario',
        'Preparada Está la Cena',
        'La Oración De Amor',
        'La Luz Del Mundo Brilla',
        'Hemos Sido Invitados',
        'Firme Estoy',
        'Divino Redentor',
        'Con Gran Emoción',
        'Centenario de la Restauración',
        'Cien Años de Misericordia',
        'Cien Años de Gran Restauración',
      ],
      newAudio: [
        'Te Alabaré',
        'Cantos Jubilosos',
        'Señor en Tu Presencia',
        'El Rey Ya Viene',
        'Ocasos',
        'Si Fui Motivo de Dolor',
        'Oh Salvador, Las Gracias Te Doy',
        'Yo Te Seguiré',
        'Isaías 12',
        'Salmo 125',
        'Amor Sin Condición',
        'Quiero Ser',
        'Guerrero Celestial',
        'Yo Tengo un Padre',
        'Digno No Soy',
        'Él Es la Luz del Mundo',
        'Imagínate Tú',
        'La Vida Se Va Como el Viento',
        'La Vida Se Va Como el Viento y Pronto en las Nubes',
        'El Valle de los Huesos Secos',
      ],
      changes: [
        'Se agregó el mixer de voces dentro de un submenú independiente.',
        'Se añadió control de volumen individual para cada voz.',
        'Se incorporaron opciones para silenciar, reactivar, restablecer y seleccionar voces en modo solo.',
        'Se mejoró la ganancia general del reproductor MIDI.',
        'Se agregó exportación individual de cada voz a MP3.',
        'Se agregó exportación del ensamble y de todas las voces.',
        'Se mejoró la compatibilidad con compases compuestos y agrupaciones rítmicas especiales.',
        'Cada pulso se reproduce y se muestra visualmente.',
        'El primer pulso de cada agrupación recibe un acento principal.',
        'Se agregaron separadores visuales para identificar las agrupaciones rítmicas.',
        'La búsqueda reconoce números escritos con dígitos o palabras en español e inglés.',
        'Se mejoró la búsqueda por nombres, temas, acentos y variantes de escritura.',
        'Se agregó feedback táctil, visual y auditivo en las anotaciones.',
        'El borrador muestra una silueta del tamaño seleccionado y funciona con un solo toque.',
        'Las anotaciones de texto muestran una caja de selección y pueden moverse y redimensionarse.',
        'Se agregó un control para eliminar textos; los controles quedan fuera de la caja de texto.',
        'Se mejoró el diseño visual de los controles de anotación.',
        'Se corrigió el problema por el que la última letra escrita podía desaparecer.',
        'Se mejoró la edición y el crecimiento del cuadro de texto.',
        'Se optimizó el historial para deshacer y rehacer cambios correctamente.',
      ],
    },
    en: {
      title: 'More control for studying each voice',
      summary: 'The MIDI player, annotations and repertoire receive a broad update to make practice more comfortable.',
      newScores: [
        'Primer Centenario',
        'Preparada Está la Cena',
        'La Oración De Amor',
        'La Luz Del Mundo Brilla',
        'Hemos Sido Invitados',
        'Firme Estoy',
        'Divino Redentor',
        'Con Gran Emoción',
        'Centenario de la Restauración',
        'Cien Años de Misericordia',
        'Cien Años de Gran Restauración',
      ],
      newAudio: [
        'Te Alabaré',
        'Cantos Jubilosos',
        'Señor en Tu Presencia',
        'El Rey Ya Viene',
        'Ocasos',
        'Si Fui Motivo de Dolor',
        'Oh Salvador, Las Gracias Te Doy',
        'Yo Te Seguiré',
        'Isaías 12',
        'Salmo 125',
        'Amor Sin Condición',
        'Quiero Ser',
        'Guerrero Celestial',
        'Yo Tengo un Padre',
        'Digno No Soy',
        'Él Es la Luz del Mundo',
        'Imagínate Tú',
        'La Vida Se Va Como el Viento',
        'La Vida Se Va Como el Viento y Pronto en las Nubes',
        'El Valle de los Huesos Secos',
      ],
      changes: [
        'Added a voice mixer inside a dedicated submenu.',
        'Added individual volume control for each voice.',
        'Added options to mute, unmute, reset and select voices in solo mode.',
        'Improved the overall gain of the MIDI player.',
        'Added individual MP3 export for each voice.',
        'Added ensemble and full voice export.',
        'Improved support for compound time signatures and special rhythmic groupings.',
        'Each beat is now played and displayed visually.',
        'The first beat of each grouping receives a primary accent.',
        'Added visual separators to identify rhythmic groupings.',
        'Search now recognizes numbers written as digits or words in both Spanish and English.',
        'Improved search by name, theme, accents and spelling variations.',
        'Added tactile, visual and audio feedback to annotations.',
        'The eraser displays an outline showing its selected size and works with a single tap.',
        'Text annotations now display a selection box and can be moved and resized.',
        'Added a control for deleting text annotations; delete and resize controls are positioned outside the text box.',
        'Improved the visual design of annotation controls.',
        'Fixed an issue that could cause the last typed character to disappear.',
        'Improved text box editing and resizing behavior.',
        'Optimized the history system for undo and redo actions.',
      ],
    },
  },
]
