export { socialLinks } from './site-data.js'

// Las fechas de tienda deben sustituirse por una fuente sincronizada cuando esté disponible.
// Actualiza estas fechas únicamente cuando la versión correspondiente ya esté publicada.
export const catalogMeta = {
  es: { lastUpdated: null, source: 'stores' },
  en: { lastUpdated: null, source: 'stores' },
}

export const releaseNotes = [
  {
    version: '2.5.2',
    releasedAt: 'Aug 26, 2026',
    dateSource: 'stores',
    es: {
      title: 'Más control para estudiar cada voz',
      summary: 'El reproductor MIDI, las anotaciones y el repertorio reciben una actualización amplia para hacer más cómodo el estudio.',
      newScores: [
        'Primer Centenario',
        'Preparada Está la Cena',
        'La Oración De Amor',
        'La Luz Del Mundo Brilla',
        'Hemos Sido Invitados',
        'Firme Estoy',
        'Divino Redentor',
        'Con Gran Emoción',
        'Centenario de la Restauración',
        'Cien Años de Misericordia',
        'Cien Años de Gran Restauración',
      ],
      newAudio: [
        'Te Alabaré',
        'Cantos Jubilosos',
        'Señor en Tu Presencia',
        'El Rey Ya Viene',
        'Ocasos',
        'Si Fui Motivo de Dolor',
        'Oh Salvador, Las Gracias Te Doy',
        'Yo Te Seguiré',
        'Isaías 12',
        'Salmo 125',
        'Amor Sin Condición',
        'Quiero Ser',
        'Guerrero Celestial',
        'Yo Tengo un Padre',
        'Digno No Soy',
        'Él Es la Luz del Mundo',
        'Imagínate Tú',
        'La Vida Se Va Como el Viento',
        'La Vida Se Va Como el Viento y Pronto en las Nubes',
        'El Valle de los Huesos Secos',
      ],
      changes: [
        'Se agregó el mixer de voces dentro de un submenú independiente.',
        'Se añadió control de volumen individual para cada voz.',
        'Se incorporaron opciones para silenciar, reactivar, restablecer y seleccionar voces en modo solo.',
        'Se mejoró la ganancia general del reproductor MIDI.',
        'Se agregó exportación individual de cada voz a MP3.',
        'Se agregó exportación del ensamble y de todas las voces.',
        'Se mejoró la compatibilidad con compases compuestos y agrupaciones rítmicas especiales.',
        'Cada pulso se reproduce y se muestra visualmente.',
        'El primer pulso de cada agrupación recibe un acento principal.',
        'Se agregaron separadores visuales para identificar las agrupaciones rítmicas.',
        'La búsqueda reconoce números escritos con dígitos o palabras en español e inglés.',
        'Se mejoró la búsqueda por nombres, temas, acentos y variantes de escritura.',
        'Se agregó feedback táctil, visual y auditivo en las anotaciones.',
        'El borrador muestra una silueta del tamaño seleccionado y funciona con un solo toque.',
        'Las anotaciones de texto muestran una caja de selección y pueden moverse y redimensionarse.',
        'Se agregó un control para eliminar textos; los controles quedan fuera de la caja de texto.',
        'Se mejoró el diseño visual de los controles de anotación.',
        'Se corrigió el problema por el que la última letra escrita podía desaparecer.',
        'Se mejoró la edición y el crecimiento del cuadro de texto.',
        'Se optimizó el historial para deshacer y rehacer cambios correctamente.',
      ],
    },
    en: {
      title: 'More control for studying each voice',
      summary: 'The MIDI player, annotations and repertoire receive a broad update to make practice more comfortable.',
      newScores: [
        'Primer Centenario',
        'Preparada Está la Cena',
        'La Oración De Amor',
        'La Luz Del Mundo Brilla',
        'Hemos Sido Invitados',
        'Firme Estoy',
        'Divino Redentor',
        'Con Gran Emoción',
        'Centenario de la Restauración',
        'Cien Años de Misericordia',
        'Cien Años de Gran Restauración',
      ],
      newAudio: [
        'Te Alabaré',
        'Cantos Jubilosos',
        'Señor en Tu Presencia',
        'El Rey Ya Viene',
        'Ocasos',
        'Si Fui Motivo de Dolor',
        'Oh Salvador, Las Gracias Te Doy',
        'Yo Te Seguiré',
        'Isaías 12',
        'Salmo 125',
        'Amor Sin Condición',
        'Quiero Ser',
        'Guerrero Celestial',
        'Yo Tengo un Padre',
        'Digno No Soy',
        'Él Es la Luz del Mundo',
        'Imagínate Tú',
        'La Vida Se Va Como el Viento',
        'La Vida Se Va Como el Viento y Pronto en las Nubes',
        'El Valle de los Huesos Secos',
      ],
      changes: [
        'Added a voice mixer inside a dedicated submenu.',
        'Added individual volume control for each voice.',
        'Added options to mute, unmute, reset and select voices in solo mode.',
        'Improved the overall gain of the MIDI player.',
        'Added individual MP3 export for each voice.',
        'Added ensemble and full voice export.',
        'Improved support for compound time signatures and special rhythmic groupings.',
        'Each beat is now played and displayed visually.',
        'The first beat of each grouping receives a primary accent.',
        'Added visual separators to identify rhythmic groupings.',
        'Search now recognizes numbers written as digits or words in both Spanish and English.',
        'Improved search by name, theme, accents and spelling variations.',
        'Added tactile, visual and audio feedback to annotations.',
        'The eraser displays an outline showing its selected size and works with a single tap.',
        'Text annotations now display a selection box and can be moved and resized.',
        'Added a control for deleting text annotations; delete and resize controls are positioned outside the text box.',
        'Improved the visual design of annotation controls.',
        'Fixed an issue that could cause the last typed character to disappear.',
        'Improved text box editing and resizing behavior.',
        'Optimized the history system for undo and redo actions.',
      ],
    },
  },
]
