export const copyEn = {
  menu: 'Open menu',
  morePages: 'More pages',
  primaryNavigation: 'Primary navigation',
  skipToContent: 'Skip to content',
  switchToSpanish: 'Change language to Spanish',
  switchToEnglish: 'Change language to English',
  playbackProgress: 'Playback progress',
  languageEnglish: 'English',
  languageSpanish: 'Spanish',
  legalInformation: 'Legal information',
  legalLinks: 'Legal links',
  lastUpdated: 'Last updated:',
  newSheetMusic: 'New sheet music',
  newRehearsalAudio: 'New rehearsal audio',
  otherChanges: 'Other changes',
  storeDatePending: 'Store date pending',
  socialMedia: 'Social media',
  socialLinkPending: '{name}: link pending',
  theme: 'Change theme',
  features: 'Features',
  product: 'The app',
  updates: 'Updates',
  catalog: 'Catalog',
  solutions: 'Choir apps',
  collaborate: 'Roadmap',
  contact: 'Contact',
  download: 'Download',
  heroEyebrow: 'Made to serve better',
  heroStart: 'Your choir, its music,',
  heroAccent: 'always with you.',
  heroLead: 'Sheet music and rehearsal audio organized in one app. Fewer folders. More music. Better preparation.',
  available: 'Available on',
  explore: 'Explore the experience',
  phoneTitle: 'My music',
  phoneSearch: 'Search music',
  appPreviewLabel: 'TLOTW Choir app preview',
  voiceAudio: 'Voice parts',
  offline: 'Works offline',
  sheetMusic: 'organized scores',
  languages: 'available languages',
  audioAvailable: 'with rehearsal audio',
  ready: 'ready when you need it',
  languageValue: 'English + Spanish',
  offlineValue: 'Offline',
  featureEyebrow: 'Everything you need',
  featureTitle: 'Rehearsing can feel simple too.',
  featureCopy: 'A tool shaped by the real experience of a choir: practical, clear and ready to go wherever you do.',
  capabilitiesEyebrow: 'Inside the app',
  capabilitiesTitle: 'Much more than a viewer.',
  capabilitiesCopy: 'Coro LLDM brings together the tools that usually end up scattered across folders, messages and different apps.',
  capabilitySearch: 'Find things quickly',
  capabilitySearchCopy: 'Normalized search by title and themes, even when numbers are written differently.',
  capabilityViewer: 'Read your way',
  capabilityViewerCopy: 'A PDF viewer with touch zoom, scrolling and an experience designed for scores.',
  capabilityAnnotations: 'Mark and annotate',
  capabilityAnnotationsCopy: 'Draw and place text over a score to remember rehearsal notes and directions.',
  capabilityOffline: 'Rehearse offline',
  capabilityOfflineCopy: 'Save important scores and materials to open them when there is no connection.',
  capabilityOrganize: 'Organize your repertoire',
  capabilityOrganizeCopy: 'Create folders, choose favorites and prepare the material for each performance.',
  capabilityAudio: 'Listen to the parts',
  capabilityAudioCopy: 'Play MIDI and rehearsal material to study the melody or your part at your own pace.',
  capabilityDownloads: 'Keep your material close',
  capabilityDownloadsCopy: 'Download scores so they remain available on your device when you need them.',
  capabilityLanguages: 'Grow with you',
  capabilityLanguagesCopy: 'A Spanish and English catalogue built to expand into more languages.',
  monetizationTitle: 'A model that sustains the project',
  monetizationCopy:
    'The free version keeps the catalogue available. Ads and moderate audio limits help cover operation and development; Premium removes ads, unlocks audio and helps us keep improving the app.',
  releaseEyebrow: 'Updates',
  releaseTitle: 'What keeps changing',
  releaseCopy: 'Longer release notes that document each improvement instead of reducing it to a single line.',
  latestVersion: 'Version',
  f1: 'Scores at hand',
  f1c: 'Find the piece you need, open it and take it with you. No folders or endless searching.',
  f2: 'Rehearse by voice',
  f2c: 'Listen to the available soprano, alto, tenor and bass parts to arrive better prepared.',
  f3: 'Even without a connection',
  f3c: 'Your scores and essential materials stay with you even when there is no signal.',
  f4: 'Made to share',
  f4c: 'Organize repertoires, prepare performances and help the whole choir sing as one.',
  demoEyebrow: 'A quick look',
  demoStart: 'A clear experience',
  demoAccent: 'for better rehearsals.',
  demoCopy: 'Explore what it feels like to browse an organized repertoire, open a score and have rehearsal material ready in seconds.',
  tryDemo: 'Try the demo',
  searchRepertoire: 'Search the repertoire...',
  catalogEyebrow: 'Visible repertoire',
  catalogTitle: 'Every score, in one place.',
  catalogCopy:
    'On the website you can listen to demos of up to 1:30 to experience the project. The app includes complete rehearsals, separated by voice parts, for the entire repertoire.',
  searchTitle: 'Search by title...',
  catalogFilters: 'Repertoire filters',
  all: 'All',
  withAudio: 'With demo',
  pending: 'Coming soon',
  audioReady: 'DEMO AVAILABLE',
  comingSoon: 'DEMO COMING SOON',
  showMore: 'Show more scores',
  catalogLoading: 'Loading repertoire…',
  catalogError: 'We could not load the repertoire. Try again.',
  retryCatalog: 'Try again',
  loadingDemo: 'Loading ensemble…',
  playingDemo: 'Ensemble rehearsal',
  stopDemo: 'Stop demo',
  previousDemo: 'Previous score',
  nextDemo: 'Next score',
  audioPendingNotice: 'The web demo for this score is still being prepared. The app includes the complete rehearsal materials.',
  audioUnavailableNotice: 'This demo is not available on this device yet. The app includes the complete rehearsal materials.',
  audioPlaybackError: 'We could not play this demo. Check your connection and try again.',
  audioPlaybackAborted: 'Playback stopped before it could start. Please try again.',
  audioPlaybackNetwork: 'We could not load the rehearsal audio. Check your connection and try again.',
  audioPlaybackDecode: 'This audio file could not be processed on this device.',
  audioPlaybackUnsupported: 'This browser does not support the available audio format.',
  moreScoresNotice: 'More scores are now visible.',
  contactIncomplete: 'Complete your name, email and message to continue.',
  contactDeliveryPending: 'Your message is ready; email delivery still needs to be enabled.',
  customEyebrow: 'Custom applications',
  bcStart: 'Your choir can have',
  bcAccent: 'its own space.',
  bcCopy:
    'Repertorio BC shows how an application can match each director’s way of working: send music to choir members, maintain an official selection and always open the right score in one unified viewer.',
  director: 'Director',
  repertoireControl: 'repertoire control',
  oneViewer: 'One viewer',
  accessibleScores: 'scores always accessible',
  designApp: 'Design an app for my choir',
  servicesEyebrow: 'We build with you',
  serviceStart: 'An app that adapts to',
  serviceAccent: 'your choir.',
  serviceCopy:
    'If your state or local choir needs its own tool, we turn its workflow, repertoire and needs into a clear, useful digital experience.',
  tellProject: 'Tell us about your project',
  service1: 'Apps for state choirs',
  service1c: 'Shared libraries, repertoire organized by church colony in Mexico and tools for coordinating choir members.',
  service2: 'Solutions for local choirs',
  service2c: 'An app focused on your rhythm, your music and the way you rehearse together.',
  service3: 'Product from start to finish',
  service3c: 'Design, development, catalog, audio, publishing and technical support.',
  collabEyebrow: 'Roadmap',
  collabStart: 'The current priority',
  collabAccent: 'for the project.',
  collabCopy:
    'For now, the confirmed work is focused on completing and publishing the rehearsal-audio demos that are still missing. No other features are presented as roadmap commitments until they are defined.',
  roadmapCurrent: 'Sample audio',
  roadmapCurrentCopy: 'Confirmed work on the material that supports the public catalogue.',
  roadmapCurrentItems: [
    'Finish rehearsal audio that is still being prepared.',
    'Check that each demo is piano, lasts 1:30 and matches the correct score.',
    'Publish the demos and keep the public catalogue up to date.',
  ],
  roadmapPending: 'Upcoming rehearsal audio',
  roadmapPendingCopy: 'These scores do not have a public demo yet. Their rehearsal audio is being prepared.',
  pendingLoading: 'Loading upcoming audio…',
  pendingEmpty: 'No pending audio is available right now.',
  contactEyebrow: 'Let’s talk',
  contactStart: 'Do you have an idea,',
  contactAccent: 'a question or a voice?',
  contactCopy: 'First choose the topic that best describes what you need. Then I will ask only for the information needed to write back.',
  contactRoutes: 'What would you like to discuss?',
  contactChoose: 'Choose an option to continue.',
  projectRoute: 'An app for my choir',
  projectRouteCopy: 'A tool designed around the way you work.',
  collabRoute: 'I want to collaborate',
  collabRouteCopy: 'Audio, repertoire, translation or testing.',
  supportRoute: 'I have a question',
  supportRouteCopy: 'About Coro LLDM or Repertorio BC.',
  contactNext: 'Your selection sets the email subject; write the rest in your own words.',
  name: 'Your name',
  namePlaceholder: 'What should we call you?',
  email: 'Your email',
  emailPlaceholder: 'name@example.com',
  message: 'Your message',
  messagePlaceholder: 'Write here...',
  send: 'Send message',
  notFoundTitle: 'This page is not in the repertoire.',
  notFoundCopy: 'The link may have changed or the page no longer exists.',
  backHome: 'Back to home',
  footerPurpose: 'Made with purpose to serve better.',
  developedBy: 'Developed by',
}
