export const copyEs = {
  menu: 'Abrir menú',
  morePages: 'Más secciones',
  primaryNavigation: 'Navegación principal',
  skipToContent: 'Saltar al contenido',
  switchToSpanish: 'Cambiar idioma a español',
  switchToEnglish: 'Cambiar idioma a inglés',
  playbackProgress: 'Progreso de reproducción',
  languageEnglish: 'Inglés',
  languageSpanish: 'Español',
  legalInformation: 'Información legal',
  legalLinks: 'Enlaces legales',
  lastUpdated: 'Última actualización:',
  newSheetMusic: 'Nuevas partituras',
  newRehearsalAudio: 'Nuevos audios de ensayo',
  otherChanges: 'Otros cambios',
  storeDatePending: 'Fecha pendiente de tienda',
  socialMedia: 'Redes sociales',
  socialLinkPending: '{name}: enlace pendiente',
  theme: 'Cambiar tema',
  features: 'Funciones',
  product: 'La aplicación',
  updates: 'Novedades',
  catalog: 'Catálogo',
  solutions: 'Apps para coros',
  collaborate: 'Roadmap',
  contact: 'Contacto',
  download: 'Descargar',
  heroEyebrow: 'Hecha para servir mejor',
  heroStart: 'Tu coro, sus cantos,',
  heroAccent: 'siempre contigo.',
  heroLead: 'Partituras y audios de ensayo organizados en una sola aplicación. Menos carpetas. Más música. Mejor preparación.',
  available: 'Disponible en',
  explore: 'Explorar la experiencia',
  phoneTitle: 'Mis cantos',
  phoneSearch: 'Buscar canto',
  appPreviewLabel: 'Vista previa de la aplicación Coro LLDM',
  voiceAudio: 'Audio por voces',
  offline: 'Funciona offline',
  sheetMusic: 'partituras organizadas',
  languages: 'idiomas disponibles',
  audioAvailable: 'con audio de ensayo',
  ready: 'lista cuando la necesitas',
  languageValue: 'Español + inglés',
  offlineValue: 'Offline',
  featureEyebrow: 'Todo lo que necesitas',
  featureTitle: 'Ensayar también puede sentirse simple.',
  featureCopy: 'Una herramienta creada desde la experiencia real de un coro: práctica, clara y lista para acompañarte donde estés.',
  capabilitiesEyebrow: 'La aplicación por dentro',
  capabilitiesTitle: 'Mucho más que un visor.',
  capabilitiesCopy:
    'Coro LLDM reúne en un mismo lugar las herramientas que normalmente terminan repartidas entre carpetas, mensajes y aplicaciones distintas.',
  capabilitySearch: 'Encuentra rápido',
  capabilitySearchCopy: 'Búsqueda normalizada por título y temas, incluso cuando escribes números de otra forma.',
  capabilityViewer: 'Lee a tu manera',
  capabilityViewerCopy: 'Visor PDF con zoom táctil, desplazamiento y una experiencia pensada para partituras.',
  capabilityAnnotations: 'Marca y anota',
  capabilityAnnotationsCopy: 'Haz trazos y coloca texto sobre la partitura para recordar indicaciones durante el ensayo.',
  capabilityOffline: 'Ensaya sin señal',
  capabilityOfflineCopy: 'Guarda tus partituras y materiales importantes para abrirlos cuando no haya conexión.',
  capabilityOrganize: 'Organiza tu repertorio',
  capabilityOrganizeCopy: 'Crea carpetas, selecciona favoritos y prepara el material que utilizarás en cada presentación.',
  capabilityAudio: 'Escucha las voces',
  capabilityAudioCopy: 'Reproduce MIDI y material de ensayo para estudiar la melodía o tu parte con más calma.',
  capabilityDownloads: 'Conserva tu material',
  capabilityDownloadsCopy: 'Descarga las partituras para tenerlas disponibles en tu dispositivo cuando las necesites.',
  capabilityLanguages: 'Crece contigo',
  capabilityLanguagesCopy: 'Catálogo en español e inglés, con una base preparada para incorporar más idiomas.',
  monetizationTitle: 'Un modelo que sostiene el proyecto',
  monetizationCopy:
    'La versión gratuita mantiene el catálogo disponible. Los anuncios y los límites moderados de audio ayudan a cubrir operación y desarrollo; Premium elimina anuncios, libera el audio y apoya que sigamos mejorando la aplicación.',
  releaseEyebrow: 'Novedades',
  releaseTitle: 'Lo que va cambiando',
  releaseCopy: 'Notas de versión más completas para documentar cada avance sin reducirlo a una sola línea.',
  latestVersion: 'Versión',
  f1: 'Partituras a la mano',
  f1c: 'Encuentra el canto que buscas, ábrelo y llévalo contigo. Sin carpetas ni búsquedas interminables.',
  f2: 'Ensaya por voces',
  f2c: 'Escucha las partes disponibles de soprano, contralto, tenor y bajo para llegar mejor preparado.',
  f3: 'Incluso sin conexión',
  f3c: 'Tus partituras y materiales importantes te acompañan también cuando no hay señal.',
  f4: 'Hecha para compartir',
  f4c: 'Organiza repertorios, prepara presentaciones y ayuda a que todo el coro cante unido.',
  demoEyebrow: 'Una probadita',
  demoStart: 'Una experiencia clara',
  demoAccent: 'para ensayar mejor.',
  demoCopy:
    'Explora cómo se siente consultar un repertorio ordenado, abrir una partitura y tener el material de ensayo listo en pocos segundos.',
  tryDemo: 'Probar la demo',
  searchRepertoire: 'Buscar en el repertorio...',
  catalogEyebrow: 'Repertorio visible',
  catalogTitle: 'Todo el material, en un mismo lugar.',
  catalogCopy:
    'En la web puedes escuchar demos de hasta 1:30 para conocer la experiencia. En la aplicación están disponibles los ensayos completos, separados por voces, para todo el repertorio.',
  searchTitle: 'Buscar por título...',
  catalogFilters: 'Filtros del repertorio',
  all: 'Todos',
  withAudio: 'Con audio',
  pending: 'Pendientes',
  audioReady: 'DEMO DISPONIBLE',
  comingSoon: 'DEMO PRÓXIMAMENTE',
  showMore: 'Mostrar más partituras',
  catalogLoading: 'Cargando repertorio…',
  catalogError: 'No pudimos cargar el repertorio. Intenta de nuevo.',
  retryCatalog: 'Reintentar',
  loadingDemo: 'Cargando ensamble…',
  playingDemo: 'Ensayo de ensamble',
  stopDemo: 'Detener demo',
  previousDemo: 'Canto anterior',
  nextDemo: 'Canto siguiente',
  audioPendingNotice: 'La demo web de este canto todavía está en preparación. En la aplicación encontrarás los ensayos completos.',
  audioUnavailableNotice: 'Esta demo todavía no está disponible para este dispositivo. En la aplicación encontrarás los ensayos completos.',
  audioPlaybackError: 'No pudimos reproducir esta demo. Revisa tu conexión e inténtalo de nuevo.',
  audioPlaybackAborted: 'La reproducción se interrumpió antes de comenzar. Inténtalo de nuevo.',
  audioPlaybackNetwork: 'No pudimos cargar el audio de ensayo. Revisa tu conexión e inténtalo de nuevo.',
  audioPlaybackDecode: 'El archivo de audio no pudo procesarse en este dispositivo.',
  audioPlaybackUnsupported: 'Este navegador no admite el formato de audio disponible.',
  moreScoresNotice: 'Se mostraron más partituras.',
  contactIncomplete: 'Completa tu nombre, correo y mensaje para continuar.',
  contactDeliveryPending: 'Tu mensaje está listo; falta habilitar el servicio de correo para enviarlo.',
  customEyebrow: 'Aplicaciones a medida',
  bcStart: 'Tu coro puede tener',
  bcAccent: 'su propio espacio.',
  bcCopy:
    'Repertorio BC es un ejemplo de cómo una aplicación puede adaptarse a la forma de trabajar de cada director: enviar los cantos a los miembros del coro, mantener una selección oficial y abrir siempre la partitura correcta desde un visor unificado.',
  director: 'Director',
  repertoireControl: 'control del repertorio',
  oneViewer: 'Un solo visor',
  accessibleScores: 'partituras siempre accesibles',
  designApp: 'Diseñar una app para mi coro',
  servicesEyebrow: 'También construimos contigo',
  serviceStart: 'Una app que se adapta a',
  serviceAccent: 'tu coro.',
  serviceCopy:
    'Si tu coro estatal o local necesita una herramienta propia, convertimos sus procesos, repertorio y necesidades en una experiencia digital clara y útil.',
  tellProject: 'Cuéntanos tu proyecto',
  service1: 'Aplicaciones para coros estatales',
  service1c:
    'Bibliotecas compartidas, repertorios organizados por colonia de México y herramientas para coordinar a los miembros del coro.',
  service2: 'Soluciones para coros locales',
  service2c: 'Una app enfocada en tu dinámica, tus cantos y la forma en que ensayan juntos.',
  service3: 'Producto de principio a fin',
  service3c: 'Diseño, desarrollo, catálogo, audio, publicación y acompañamiento técnico.',
  collabEyebrow: 'Hoja de ruta',
  collabStart: 'La prioridad actual',
  collabAccent: 'del proyecto.',
  collabCopy:
    'Por ahora, el trabajo confirmado está concentrado en completar y publicar los audios de muestra que todavía faltan. No presento otras funciones como parte del roadmap hasta que estén definidas.',
  roadmapCurrent: 'Audios de muestra',
  roadmapCurrentCopy: 'Trabajo confirmado sobre el material que acompaña al catálogo público.',
  roadmapCurrentItems: [
    'Terminar los audios de ensayo que todavía están en preparación.',
    'Comprobar que cada demo sea de piano, dure 1:30 y corresponda al canto correcto.',
    'Publicar las demos y mantener actualizado el catálogo público.',
  ],
  roadmapPending: 'Próximos audios de ensayo',
  roadmapPendingCopy: 'Estos cantos todavía no tienen demo pública. El audio de ensayo se está preparando.',
  pendingLoading: 'Cargando próximos audios…',
  pendingEmpty: 'No hay audios pendientes disponibles en este momento.',
  contactEyebrow: 'Hablemos',
  contactStart: '¿Tienes una idea,',
  contactAccent: 'una pregunta o una voz?',
  contactCopy:
    'Primero elige el tema que mejor describe lo que necesitas. Después te pediré solo la información necesaria para escribirte.',
  contactRoutes: '¿De qué quieres hablar?',
  contactChoose: 'Selecciona una opción para continuar.',
  projectRoute: 'Una app para mi coro',
  projectRouteCopy: 'Una herramienta pensada para tu forma de trabajar.',
  collabRoute: 'Quiero colaborar',
  collabRouteCopy: 'Audio, repertorio, traducción o pruebas.',
  supportRoute: 'Tengo una pregunta',
  supportRouteCopy: 'Sobre Coro LLDM o Repertorio BC.',
  contactNext: 'Tu selección define el asunto del correo; escribe el resto con tus propias palabras.',
  name: 'Tu nombre',
  namePlaceholder: '¿Cómo te llamas?',
  email: 'Tu correo',
  emailPlaceholder: 'nombre@ejemplo.com',
  message: 'Tu mensaje',
  messagePlaceholder: 'Escribe aquí...',
  send: 'Enviar mensaje',
  notFoundTitle: 'Esta página no está en el repertorio.',
  notFoundCopy: 'Puede que el enlace haya cambiado o que la página ya no exista.',
  backHome: 'Volver al inicio',
  footerPurpose: 'Hecho con propósito para servir mejor.',
  developedBy: 'Desarrollado por',
}
